language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
   - composer install

script: phpunit ./tests

notifications:
  email: false
  irc:
    channels:
      secure: "P04qAQuBkR3eD9nR5KCEocg+vcbV7VSgoIYYwXFjuM1qi8DijzSw+k5z0jMmFhQcB1IQ/Y7Fbi8Pm8VSxuJHcqaigmdVF7rjf5951lytcq+rFSsTjafJcqIe9156kPwFvJKRhImFARKuHs5UNokZ+fH2GIRWghvJIGosRqXcGfE="
    on_success: change
    on_failure: always
